version: "3.9"
services:
  postgres_ecommerce:
    container_name: postgres_ecommerce
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'